### PR TITLE
Improved typing for validators

### PR DESCRIPTION
**Pull request by lalten**
Previously when using the `Measurement.with_validator()` method in otherwise strictly typed user code, the line needed a `# type: ignore[no-untyped-call]`.
With this patch applied, this is no longer necessary.

---
This change is [Reviewable](https://reviewable.io/reviews/google/openhtf/995)

### CODE REVIEW

**Comment by lalten** [comment]
@cricdecyan I rebased to latest master, would be happy about your review

**Comment by cricdecyan** [comment]
@lalten I will review next week.

**Review by cricdecyan — APPROVED** [review]

**Comment by cricdecyan** [comment]
@lalten I approved, please rebase the PR so we can merge it.

**Comment by lalten** [comment]
@cricdecyan lgtm

**Pull request merged**
