### PR TITLE
bugfix WithArgs typo

### PR DESCRIPTION
**Pull request by grybmadsci**
Faaaaaarz.  Unit test yo shit.

### CODE REVIEW

**Comment by fahhem** [comment]
I test it! Internally! Copy-paste problems :) I've been overworked lately, assign a bug to unit-test phase-info stuff to me and I'll get to it next week

**Comment by grybmadsci** [comment]
haha no worries, just giving you a hard time ;)  we all need to get better about unit testing in general, you just happened to cause the first obvious breakage to harass over lol... issue filed, no rush.

**Comment by grybmadsci** [comment]
ermergerd herps to jermp threw.

**Comment by fahhem** [comment]
Hey, I haven't broken the tests yet :P

**Pull request merged**
