### PR TITLE
Fix for issue 820

### PR DESCRIPTION
**Pull request by kwmlodozeniec**
This change is [Reviewable](https://reviewable.io/reviews/google/openhtf/822)

### CODE REVIEW

**Comment by kdsudac** [comment]
This doesn't actually work.

**Comment by kdsudac** [comment]
`from openhtf.output.web_gui import web_launcher` is the import you want.

Running simple fixes like this manually is a good habit to get into because our unit test coverage isn't 100%.  In this case just running `python examples/frontend_example.py`.

Thanks for fixing.

**Comment by kwmlodozeniec** [comment]
The import you suggested doesn't work.

**Comment by kdsudac** [comment]
Doesn't work as in you get a traceback on an import error?

or doesn't work as in your don't see the frontend pop-up?

**Comment by kwmlodozeniec** [comment]
Import error.

**Comment by arsharma1** [comment]
This pull is not needed for main, where it has already been fixed.  It's only an issue in the 1.3.0 release, which means we need a new one.

**Comment by kwmlodozeniec** [comment]
So, can this PR be closed?

**Pull request closed without merging**
