### PR TITLE
Cleanup and update deps

### PR DESCRIPTION
**Pull request by fahhem**
(Just the last commit, the rest are from #54)

Now that it's all inside setup.py, you should run `python setup.py install` before other things. However, to install with -e as before, use `python setup.py develop`, and `python setup.py test` will install test requirements as well.

### CODE REVIEW

**Comment by fahhem** [comment]
Fixes #48

**Comment by jettisonjoe** [comment]
Looks like this needs a rebase now that your first PR was merged.

**Comment by fahhem** [comment]
Rebased

**Comment by jettisonjoe** [comment]
Cool. Merging.

**Pull request merged**
