### PR TITLE
Raise pylint compliance.

### PR DESCRIPTION
**Pull request by jettisonjoe**
After this PR, pylint compliance will be up to 9.72/10. The few violations that are left are either:
  * conf module names that should be addressed via an update to our pylint plugins
  * TODO's for other people
  * Weirdness that we should discuss and resolve.

See [the placeholder PR](https://github.com/jettisonjoe/openhtf/pull/1) against my fork for previous review history.

---
This change is [Reviewable](https://reviewable.io/reviews/google/openhtf/402)

### CODE REVIEW

**Comment by jettisonjoe** [comment]
@fahhem @grybmadsci this needs a final review before merge. PTAL when you get a chance. Thanks!

**Comment by fahhem** [comment]
Thanks for this! I'll have a ton of work to do when I import this, but the benefit to the code and future reviews will hopefully be worth it.

---

Reviewed 8 of 51 files at r1, 2 of 38 files at r2, 34 of 65 files at r3, 28 of 36 files at r4.
Review status: all files reviewed at latest revision, 19 unresolved discussions.

---

*[Makefile, line 1 \[r4\]](https://reviewable.io:443/reviews/google/openhtf/402#-KPSYaAjdbHQN8ZOwqn4:-KPSYaAjdbHQN8ZOwqn5:b4t9wf2) ([raw file](https://github.com/google/openhtf/blob/3ce46080f17b22bf99da05a9e26695db980d0a5f/Makefile#L1)):*
> ```Makefile
> # Makefile for Sphinx documentation
> ```

Can this and other docs related stuff go into a docs/ folder?

---

*[pylintrc, line 15 \[r4\]](https://reviewable.io:443/reviews/google/openhtf/402#-KPS_6ZYLAxicNDRq7f-:-KPS_6ZYLAxicNDRq7f0:b-1yu7vl) ([raw file](https://github.com/google/openhtf/blob/3ce46080f17b22bf99da05a9e26695db980d0a5f/pylintrc#L15)):*
> ```
> # Add files or directories to the blacklist. They should be base names, not
> # paths.
> ignore=CVS,guzzle_pb2.py,test_runs_pb2.py,units_pb2.py
> ```

ignore-patterns=.*_pb2.py

Turns out this file is documented as little as possible, so I had to look at the source: https://github.com/PyCQA/pylint/blob/ec09cc75786e794d9f15654da5e1ed2d6c120fcd/pylint/lint.py#L276

---

*[pylintrc, line 44 \[r4\]](https://reviewable.io:443/reviews/google/openhtf/402#-KPS_tmRUCljQtOzyMYI:-KPS_tmRUCljQtOzyMYJ:b-oixbq7) ([raw file](https://github.com/google/openhtf/blob/3ce46080f17b22bf99da05a9e26695db980d0a5f/pylintrc#L44)):*
> ```
> # Supress all import errors until SublimeLinter-pylint gets virtualenv support.
> # Supress errors about locally defined disables.
> disable=import-error,I0011,W0223,W0212
> ```

use the names please:

disable=import-error,I0011,abstractmethod,protected-access

Now that I know the names, these seem bad to have. Was pylint: disable= not working?

---

*[unit_result.txt, line 2 \[r4\]](https://reviewable.io:443/reviews/google/openhtf/402#-KPSabFhsFQMmkuXss4w:-KPSabFinq1b-iy4VQLk:b2xzsq1) ([raw file](https://github.com/google/openhtf/blob/3ce46080f17b22bf99da05a9e26695db980d0a5f/unit_result.txt#L2)):*
> ```
> running test
> Searching for pytest-cov>=2.2.1
> ```

I don't think you meant to check this in?

---

*[examples/example_plug.py, line 25 \[r4\]](https://reviewable.io:443/reviews/google/openhtf/402#-KPSaht-T09khjPlKyyp:-KPSaht-T09khjPlKyyq:b2t6hdl) ([raw file](https://github.com/google/openhtf/blob/3ce46080f17b22bf99da05a9e26695db980d0a5f/examples/example_plug.py#L25)):*
> ```Python
> 
> 
> conf.declare('example_plug_increment_size', default_value=1,
> ```

not sure why you added `_size` here. increment seemed fine to me

---

*[openhtf/bin/units_from_xls.py, line 122 \[r4\]](https://reviewable.io:443/reviews/google/openhtf/402#-KPSdFWzCqY6ykNvIx9t:-KPSdFX-oBZQFukrE9uz:bfymh7g) ([raw file](https://github.com/google/openhtf/blob/3ce46080f17b22bf99da05a9e26695db980d0a5f/openhtf/bin/units_from_xls.py#L122)):*
> ```Python
> # pylint: enable=line-too-long
> 
> class UnitLookup(object):  # pylint: disable=too-few-public-methods
> ```

This seems like everybody disables this in their pylintrc, and I agree with them!

---

*[openhtf/exe/__init__.py, line 65 \[r4\]](https://reviewable.io:443/reviews/google/openhtf/402#-KPSdvSPwvrIWJVqWtFh:-KPSdvSQK9igWkgwvTAq:bms7p1) ([raw file](https://github.com/google/openhtf/blob/3ce46080f17b22bf99da05a9e26695db980d0a5f/openhtf/exe/__init__.py#L65)):*
> ```Python
>     self._teardown_function = (
>         teardown_function and
>         openhtf.PhaseDescriptor.wrap_or_copy(
> ```

`cast` seems like a better name, what do you think? Or `cast_from`?

---

*[openhtf/exe/triggers.py, line 38 \[r4\]](https://reviewable.io:443/reviews/google/openhtf/402#-KPSfGQw09iuOpdq5srq:-KPSfGQxy-UGiS1VL2F-:b-y10zbb) ([raw file](https://github.com/google/openhtf/blob/3ce46080f17b22bf99da05a9e26695db980d0a5f/openhtf/exe/triggers.py#L38)):*
> ```Python
> 
> def auto_start():  # pylint: disable=invalid-name
>   """DEPRECATED, use a lambda instead."""
> ```

I think we can remove this now, the API has changed so drastically...

---

*[openhtf/io/http_api.py, line 110 \[r4\]](https://reviewable.io:443/reviews/google/openhtf/402#-KPSfZ__b6bLWhl0TJ8i:-KPSfZ__b6bLWhl0TJ8j:b-sinldx) ([raw file](https://github.com/google/openhtf/blob/3ce46080f17b22bf99da05a9e26695db980d0a5f/openhtf/io/http_api.py#L110)):*
> ```Python
>                  msg_format%args)
> 
>     def do_get(self):  # pylint: disable=invalid-name
> ```

has this been tested? I don't think this works?

---

*[openhtf/io/frontend/__init__.py, line 199 \[r4\]](https://reviewable.io:443/reviews/google/openhtf/402#-KPSgYCSEOZEARM44thB:-KPSgYCSEOZEARM44thC:b-76q5it) ([raw file](https://github.com/google/openhtf/blob/3ce46080f17b22bf99da05a9e26695db980d0a5f/openhtf/io/frontend/__init__.py#L199)):*
> ```Python
> 
>   @classproperty
>   def _lock(cls):  # pylint: disable=no-self-argument
> ```

Maybe add a TODO to openhtf.util.classproperty to create a pylint plugin for it?

---

*[openhtf/io/output/console_summary.py, line 59 \[r4\]](https://reviewable.io:443/reviews/google/openhtf/402#-KPSgo2ypDxSTVvm6Jw9:-KPSgo2ypDxSTVvm6JwA:b-jfclw6) ([raw file](https://github.com/google/openhtf/blob/3ce46080f17b22bf99da05a9e26695db980d0a5f/openhtf/io/output/console_summary.py#L59)):*
> ```Python
>             output_lines.append('%sfailed_item: %s' % (self.indent,
>                                                        result.name))
>             output_lines.append('%smeasured_value: %s' %
> ```

```py
             output_lines.append('%smeasured_value: %s' %
                                 (self.indent*2, str(measured[result.name])))
             output_lines.append('%svalidators:' % (self.indent*2))
             for validator in result.validators:
               output_lines.append('%svalidator: %s' %
                                   (self.indent*3, str(validator)))
  
         phase_result = phase.result.phase_result
         if not phase_result:   #Timeout
           output_lines.append('timeout phase: %s [ran for %.2f sec]' %
                               (phase.name, phase_time_sec))
         elif 'CONTINUE' not in str(phase_result):  #Exception
           output_lines.append('%sexception type: %s' % (
```

This file isn't really consistent in regards to whether to put the `(` on the same line as the `%` and whether to put both parts of a two-tuple on the same line

---

*[openhtf/util/argv.py, line 23 \[r4\]](https://reviewable.io:443/reviews/google/openhtf/402#-KPSibThWFP6HP4UkWZX:-KPSibThWFP6HP4UkWZY:byny1ry) ([raw file](https://github.com/google/openhtf/blob/3ce46080f17b22bf99da05a9e26695db980d0a5f/openhtf/util/argv.py#L23)):*
> ```Python
> 
> def ModuleParser():
>   return argparse.ArgumentParser(add_help=False)
> ```

I thought this was to match the open-source community better? If we go with 2-spaces, that's a significant departure from PEP8

---

*[openhtf/util/measurements.py, line 120 \[r4\]](https://reviewable.io:443/reviews/google/openhtf/402#-KPSjIsLwLMYT_iywy68:-KPSjIsMavUGKdOjDm2I:b-iz1py8) ([raw file](https://github.com/google/openhtf/blob/3ce46080f17b22bf99da05a9e26695db980d0a5f/openhtf/util/measurements.py#L120)):*
> ```Python
>     docstring: Optional string describing this measurement.
>     units: UOM code of the units for the measurement being taken.
>     dimensions: Tuple of UOM codes for units of dimensions.
> ```

existing: `mutablerecords` allows creating attributes with leading underscores. It seems like most of these are meant to be python-private since they all get set indirectly by methods in this class

---

*[openhtf/util/measurements.py, line 144 \[r4\]](https://reviewable.io:443/reviews/google/openhtf/402#-KPSjBPWsK8cnZPsgbhw:-KPSjBPWsK8cnZPsgbhx:b-f1csog) ([raw file](https://github.com/google/openhtf/blob/3ce46080f17b22bf99da05a9e26695db980d0a5f/openhtf/util/measurements.py#L144)):*
> ```Python
>     super(Measurement, self).__setattr__(attr, value)
>     # When dimensions changes, we may need to update our measured_value type.
>     if attr == 'dimensions':
> ```

existing: This check should go in `with_dimensions()` not here

---

*[openhtf/util/measurements.py, line 161 \[r4\]](https://reviewable.io:443/reviews/google/openhtf/402#-KPSivf7NxtMBX4-q65A:-KPSivf7NxtMBX4-q65B:b-y8dm4m) ([raw file](https://github.com/google/openhtf/blob/3ce46080f17b22bf99da05a9e26695db980d0a5f/openhtf/util/measurements.py#L161)):*
> ```Python
>     self._notification_cb = notification_cb
>     if not notification_cb and self.dimensions:
>       self.measured_value.notify_value_set = None  # pylint: disable=attribute-defined-outside-init
> ```

this isn't defining an attribute?

---

*[pylint_plugins/conf_plugin.py, line 11 \[r4\]](https://reviewable.io:443/reviews/google/openhtf/402#-KPSkQ3jeWJupj7pvCMu:-KPSkQ3jeWJupj7pvCMv:b1j0p2b) ([raw file](https://github.com/google/openhtf/blob/3ce46080f17b22bf99da05a9e26695db980d0a5f/pylint_plugins/conf_plugin.py#L11)):*
> ```Python
> 
> # Store a reference to the openhtf.conf module node.
> class clss(object):
> ```

`clss`?

---

*[pylint_plugins/conf_plugin.py, line 16 \[r4\]](https://reviewable.io:443/reviews/google/openhtf/402#-KPSkS6d9EK_0mTPjWMn:-KPSkS6d9EK_0mTPjWMo:bpdzcns) ([raw file](https://github.com/google/openhtf/blob/3ce46080f17b22bf99da05a9e26695db980d0a5f/pylint_plugins/conf_plugin.py#L16)):*
> ```Python
>   current_root = None
> 
> def trans_expr(node):
> ```

sorry, these names are indecipherable

---

*[pylint_plugins/conf_plugin.py, line 18 \[r4\]](https://reviewable.io:443/reviews/google/openhtf/402#-KPSkcJq3ZLDaRJXwWBW:-KPSkcJq3ZLDaRJXwWBX:b-bkjxbi) ([raw file](https://github.com/google/openhtf/blob/3ce46080f17b22bf99da05a9e26695db980d0a5f/pylint_plugins/conf_plugin.py#L18)):*
> ```Python
> def trans_expr(node):
>   # Check if it's a call to conf.Declare.
>   if (isinstance(node.func, astroid.Attribute) and
> ```

2-spaces and many levels of indentation don't mix well. Consider negating this logic and putting a `return` after it

---

*[pylint_plugins/mutablerecords_plugin.py, line 12 \[r4\]](https://reviewable.io:443/reviews/google/openhtf/402#-KPSlDmyQeDLEY_EdtTq:-KPSlDmyQeDLEY_EdtTr:b-p8wca2) ([raw file](https://github.com/google/openhtf/blob/3ce46080f17b22bf99da05a9e26695db980d0a5f/pylint_plugins/mutablerecords_plugin.py#L12)):*
> ```Python
> 
> def mutables_transform(cls):
>   #checking if it's inheriting from a mutablerecords declaration
> ```

does pylint not enforce a space after #?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/openhtf/402#-:-KPSlx7k7Xu_696vxBTZ:buhypfj)*

**Comment by jettisonjoe** [comment]
Review status: all files reviewed at latest revision, 19 unresolved discussions.

---

*[Makefile, line 1 \[r4\]](https://reviewable.io:443/reviews/google/openhtf/402#-KPSYaAjdbHQN8ZOwqn4:-KPZfd6bYMoYMHNqpHs1:b-ypf60a) ([raw file](https://github.com/google/openhtf/blob/3ce46080f17b22bf99da05a9e26695db980d0a5f/Makefile#L1)):*
<details><summary><i>Previously, fahhem (Fahrzin Hemmati) wrote…</i></summary>
> Can this and other docs related stuff go into a docs/ folder?
</details>
Oops, I think the Sphinx stuff was something Maddy started but didn't finish yet. I'm gonna take this file out for now as it should be in a separate PR anyway.

---

*[pylintrc, line 15 \[r4\]](https://reviewable.io:443/reviews/google/openhtf/402#-KPS_6ZYLAxicNDRq7f-:-KPZh1c_dOFN3cJmQ4pi:bq702pm) ([raw file](https://github.com/google/openhtf/blob/3ce46080f17b22bf99da05a9e26695db980d0a5f/pylintrc#L15)):*
<details><summary><i>Previously, fahhem (Fahrzin Hemmati) wrote…</i></summary>
> ignore-patterns=.*_pb2.py
> 
> Turns out this file is documented as little as possible, so I had to look at the source: https://github.com/PyCQA/pylint/blob/ec09cc75786e794d9f15654da5e1ed2d6c120fcd/pylint/lint.py#L276
</details>
Good find, thanks.

---

*[pylintrc, line 44 \[r4\]](https://reviewable.io:443/reviews/google/openhtf/402#-KPS_tmRUCljQtOzyMYI:-KPZjO0gDSxtOkFZkDO6:b-yq858z) ([raw file](https://github.com/google/openhtf/blob/3ce46080f17b22bf99da05a9e26695db980d0a5f/pylintrc#L44)):*
<details><summary><i>Previously, fahhem (Fahrzin Hemmati) wrote…</i></summary>
> use the names please:
> 
> disable=import-error,I0011,abstractmethod,protected-access
> 
> Now that I know the names, these seem bad to have. Was pylint: disable= not working?
</details>
Not sure. @maddychan, can you clarig

---

*[unit_result.txt, line 2 \[r4\]](https://reviewable.io:443/reviews/google/openhtf/402#-KPSabFhsFQMmkuXss4w:-KPZjff4U6iiLtDdLdXj:b-80bnvp) ([raw file](https://github.com/google/openhtf/blob/3ce46080f17b22bf99da05a9e26695db980d0a5f/unit_result.txt#L2)):*
<details><summary><i>Previously, fahhem (Fahrzin Hemmati) wrote…</i></summary>
> I don't think you meant to check this in?
</details>
True.

---

*[examples/example_plug.py, line 25 \[r4\]](https://reviewable.io:443/reviews/google/openhtf/402#-KPSaht-T09khjPlKyyp:-KPZkDsAHe6TEbBPqGSb:b1l0dwo) ([raw file](https://github.com/google/openhtf/blob/3ce46080f17b22bf99da05a9e26695db980d0a5f/examples/example_plug.py#L25)):*
<details><summary><i>Previously, fahhem (Fahrzin Hemmati) wrote…</i></summary>
> not sure why you added `_size` here. increment seemed fine to me
</details>
The old method `Increment` became `increment`, which meant I had to come up with a new name for either it or the former `increment` attribute. I changed the attr to `increment_size` and thus the config key to match. Open to other suggestions here.

---

*[openhtf/bin/units_from_xls.py, line 122 \[r4\]](https://reviewable.io:443/reviews/google/openhtf/402#-KPSdFWzCqY6ykNvIx9t:-KPZkmZxgSO8QTKrhkLl:b-o69n7u) ([raw file](https://github.com/google/openhtf/blob/3ce46080f17b22bf99da05a9e26695db980d0a5f/openhtf/bin/units_from_xls.py#L122)):*
<details><summary><i>Previously, fahhem (Fahrzin Hemmati) wrote…</i></summary>
> This seems like everybody disables this in their pylintrc, and I agree with them!
</details>
I'm down.

---

*[openhtf/exe/__init__.py, line 65 \[r4\]](https://reviewable.io:443/reviews/google/openhtf/402#-KPSdvSPwvrIWJVqWtFh:-KPZlBoYhlCc54DTUVJk:bawkn1u) ([raw file](https://github.com/google/openhtf/blob/3ce46080f17b22bf99da05a9e26695db980d0a5f/openhtf/exe/__init__.py#L65)):*
<details><summary><i>Previously, fahhem (Fahrzin Hemmati) wrote…</i></summary>
> `cast` seems like a better name, what do you think? Or `cast_from`?
</details>
I'm open to `cast_from`. @grybmasci, any thoughts/objections here?

---

*[openhtf/exe/triggers.py, line 38 \[r4\]](https://reviewable.io:443/reviews/google/openhtf/402#-KPSfGQw09iuOpdq5srq:-KPZlSh_4-7Sb67IdmlQ:b-1bklxw) ([raw file](https://github.com/google/openhtf/blob/3ce46080f17b22bf99da05a9e26695db980d0a5f/openhtf/exe/triggers.py#L38)):*
<details><summary><i>Previously, fahhem (Fahrzin Hemmati) wrote…</i></summary>
> I think we can remove this now, the API has changed so drastically...
</details>
Fair enough. Better to remove than to rename, I suppose.

---

*[openhtf/io/http_api.py, line 110 \[r4\]](https://reviewable.io:443/reviews/google/openhtf/402#-KPSfZ__b6bLWhl0TJ8i:-KPZldY8PNjkKjCsIN9O:b-u7dxni) ([raw file](https://github.com/google/openhtf/blob/3ce46080f17b22bf99da05a9e26695db980d0a5f/openhtf/io/http_api.py#L110)):*
<details><summary><i>Previously, fahhem (Fahrzin Hemmati) wrote…</i></summary>
> has this been tested? I don't think this works?
</details>
You're correct. But maybe we can just retire the http API at this point.

---

*[openhtf/io/frontend/__init__.py, line 199 \[r4\]](https://reviewable.io:443/reviews/google/openhtf/402#-KPSgYCSEOZEARM44thB:-KPZm5nTn72N7Eb_imNK:b32vyd) ([raw file](https://github.com/google/openhtf/blob/3ce46080f17b22bf99da05a9e26695db980d0a5f/openhtf/io/frontend/__init__.py#L199)):*
<details><summary><i>Previously, fahhem (Fahrzin Hemmati) wrote…</i></summary>
> Maybe add a TODO to openhtf.util.classproperty to create a pylint plugin for it?
</details>
Kk

---

*[openhtf/io/output/console_summary.py, line 59 \[r4\]](https://reviewable.io:443/reviews/google/openhtf/402#-KPSgo2ypDxSTVvm6Jw9:-KP_-Jn-DlvOjngflRgZ:bvagjis) ([raw file](https://github.com/google/openhtf/blob/3ce46080f17b22bf99da05a9e26695db980d0a5f/openhtf/io/output/console_summary.py#L59)):*
<details><summary><i>Previously, fahhem (Fahrzin Hemmati) wrote…</i></summary>
> ```py
>              output_lines.append('%smeasured_value: %s' %
>                                  (self.indent*2, str(measured[result.name])))
>              output_lines.append('%svalidators:' % (self.indent*2))
>              for validator in result.validators:
>                output_lines.append('%svalidator: %s' %
>                                    (self.indent*3, str(validator)))
>   
>          phase_result = phase.result.phase_result
>          if not phase_result:   #Timeout
>            output_lines.append('timeout phase: %s [ran for %.2f sec]' %
>                                (phase.name, phase_time_sec))
>          elif 'CONTINUE' not in str(phase_result):  #Exception
>            output_lines.append('%sexception type: %s' % (
> ```
> 
> This file isn't really consistent in regards to whether to put the `(` on the same line as the `%` and whether to put both parts of a two-tuple on the same line
</details>
Cleaned that up and standardized it a bit.

---

*[openhtf/util/argv.py, line 23 \[r4\]](https://reviewable.io:443/reviews/google/openhtf/402#-KPSibThWFP6HP4UkWZX:-KP_-ROtwwsFQUPXKwSh:b-4hq4a0) ([raw file](https://github.com/google/openhtf/blob/3ce46080f17b22bf99da05a9e26695db980d0a5f/openhtf/util/argv.py#L23)):*
<details><summary><i>Previously, fahhem (Fahrzin Hemmati) wrote…</i></summary>
> I thought this was to match the open-source community better? If we go with 2-spaces, that's a significant departure from PEP8
</details>
For sure we want to move to 4 spaces eventually, but that's kind of a big job since it's going to involve re-tooling a lot of line joins. I think we should start with the test author impacting stuff and tackle the indentation later (but still soon).

---

*[openhtf/util/measurements.py, line 120 \[r4\]](https://reviewable.io:443/reviews/google/openhtf/402#-KPSjIsLwLMYT_iywy68:-KP_-zeb60Z9QAdWFZd_:b-dowzsx) ([raw file](https://github.com/google/openhtf/blob/3ce46080f17b22bf99da05a9e26695db980d0a5f/openhtf/util/measurements.py#L120)):*
<details><summary><i>Previously, fahhem (Fahrzin Hemmati) wrote…</i></summary>
> existing: `mutablerecords` allows creating attributes with leading underscores. It seems like most of these are meant to be python-private since they all get set indirectly by methods in this class
</details>
That's a fair point, but should be filed as a separate issue since this PR is just for pylint compliance work. I would prefer not to handle the 'existing' stuff in these PyPI-gating reviews and to address them in separate PR's later, unless they affect the test authoring API.

---

*[openhtf/util/measurements.py, line 144 \[r4\]](https://reviewable.io:443/reviews/google/openhtf/402#-KPSjBPWsK8cnZPsgbhw:-KP_0oEYHA_RPPMAhAcR:b-p7w1rt) ([raw file](https://github.com/google/openhtf/blob/3ce46080f17b22bf99da05a9e26695db980d0a5f/openhtf/util/measurements.py#L144)):*
<details><summary><i>Previously, fahhem (Fahrzin Hemmati) wrote…</i></summary>
> existing: This check should go in `with_dimensions()` not here
</details>
See prior comment on 'existing' comments.

---

*[openhtf/util/measurements.py, line 161 \[r4\]](https://reviewable.io:443/reviews/google/openhtf/402#-KPSivf7NxtMBX4-q65A:-KP_1FSOXIQ1r644i1L3:bbk50um) ([raw file](https://github.com/google/openhtf/blob/3ce46080f17b22bf99da05a9e26695db980d0a5f/openhtf/util/measurements.py#L161)):*
<details><summary><i>Previously, fahhem (Fahrzin Hemmati) wrote…</i></summary>
> this isn't defining an attribute?
</details>
Not sure how that got in there. Removing.

---

*[pylint_plugins/conf_plugin.py, line 11 \[r4\]](https://reviewable.io:443/reviews/google/openhtf/402#-KPSkQ3jeWJupj7pvCMu:-KP_4xP1cI2jwQ3-VrQs:bxvz0nz) ([raw file](https://github.com/google/openhtf/blob/3ce46080f17b22bf99da05a9e26695db980d0a5f/pylint_plugins/conf_plugin.py#L11)):*
<details><summary><i>Previously, fahhem (Fahrzin Hemmati) wrote…</i></summary>
> `clss`?
</details>
Updating to be more clear.

---

*[pylint_plugins/conf_plugin.py, line 16 \[r4\]](https://reviewable.io:443/reviews/google/openhtf/402#-KPSkS6d9EK_0mTPjWMn:-KP_5-3YI49_-H52LaML:btzzxrb) ([raw file](https://github.com/google/openhtf/blob/3ce46080f17b22bf99da05a9e26695db980d0a5f/pylint_plugins/conf_plugin.py#L16)):*
<details><summary><i>Previously, fahhem (Fahrzin Hemmati) wrote…</i></summary>
> sorry, these names are indecipherable
</details>
Agreed. Will update to make more clear.

---

*[pylint_plugins/conf_plugin.py, line 18 \[r4\]](https://reviewable.io:443/reviews/google/openhtf/402#-KPSkcJq3ZLDaRJXwWBW:-KP_5ibI57ILuaE5gnvl:b-1si82y) ([raw file](https://github.com/google/openhtf/blob/3ce46080f17b22bf99da05a9e26695db980d0a5f/pylint_plugins/conf_plugin.py#L18)):*
<details><summary><i>Previously, fahhem (Fahrzin Hemmati) wrote…</i></summary>
> 2-spaces and many levels of indentation don't mix well. Consider negating this logic and putting a `return` after it
</details>
Agreed, will fix.

---

*[pylint_plugins/mutablerecords_plugin.py, line 12 \[r4\]](https://reviewable.io:443/reviews/google/openhtf/402#-KPSlDmyQeDLEY_EdtTq:-KP_6h3j7d-G_TtRLtm5:bpm5shz) ([raw file](https://github.com/google/openhtf/blob/3ce46080f17b22bf99da05a9e26695db980d0a5f/pylint_plugins/mutablerecords_plugin.py#L12)):*
<details><summary><i>Previously, fahhem (Fahrzin Hemmati) wrote…</i></summary>
> does pylint not enforce a space after #?
</details>
I don't know, but I'll clean up these comments.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/openhtf/402)*

**Comment by jettisonjoe** [comment]
Responded to feedback. PTAL.

---

Review status: all files reviewed at latest revision, 19 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/openhtf/402#-:-KP_7qUQVXvOSSD_zjy5:b-401moc)*

**Comment by fahhem** [comment]
Reviewed 9 of 9 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[pylintrc, line 44 \[r4\]](https://reviewable.io:443/reviews/google/openhtf/402#-KPS_tmRUCljQtOzyMYI:-KP_8af4MfXnMJOYJU3k:b-ljanyp) ([raw file](https://github.com/google/openhtf/blob/3ce46080f17b22bf99da05a9e26695db980d0a5f/pylintrc#L44)):*
<details><summary><i>Previously, jettisonjoe (Joe Ethier) wrote…</i></summary>
> Not sure. @maddychan, can you clarig
</details>
protected-access is really beneficial, and if we're getting a bunch of them I'd be surprised. abstractmethod shouldn't show up much in this codebase either, and I think it's worth the pylint disable comments since it'll usually be followed up with which abstract methods weren't implemented

---

*[openhtf/bin/units_from_xls.py, line 122 \[r4\]](https://reviewable.io:443/reviews/google/openhtf/402#-KPSdFWzCqY6ykNvIx9t:-KP_DECQ7OSC7pC3ACIw:bw4hw9h) ([raw file](https://github.com/google/openhtf/blob/3ce46080f17b22bf99da05a9e26695db980d0a5f/openhtf/bin/units_from_xls.py#L122)):*
<details><summary><i>Previously, jettisonjoe (Joe Ethier) wrote…</i></summary>
> I'm down.
</details>
You added this to pylintrc, but didn't remove it from here (is it anywhere else, too?)

---

*[openhtf/io/http_api.py, line 110 \[r4\]](https://reviewable.io:443/reviews/google/openhtf/402#-KPSfZ__b6bLWhl0TJ8i:-KP_DOT-wKIwCQOFWYDt:b-y4nunx) ([raw file](https://github.com/google/openhtf/blob/3ce46080f17b22bf99da05a9e26695db980d0a5f/openhtf/io/http_api.py#L110)):*
<details><summary><i>Previously, jettisonjoe (Joe Ethier) wrote…</i></summary>
> You're correct. But maybe we can just retire the http API at this point.
</details>
If station API is tested and used by someone sure. I haven't been able to import it yet due to the API changes and looming testing deadlines so I don't know if it works for us

---

*[pylint_plugins/conf_plugin.py, line 26 \[r5\]](https://reviewable.io:443/reviews/google/openhtf/402#-KP_CWWv3B3PmX9AKveJ:-KP_CWWv3B3PmX9AKveK:bsodm2q) ([raw file](https://github.com/google/openhtf/blob/27cebec4ead3df2737be3781984aaf0d2ded11ee/pylint_plugins/conf_plugin.py#L26)):*
> ```Python
> 
> 
> class SavedInfo(object):
> ```

This is a namespace of variables? Why not just module-level variables?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/openhtf/402)*

**Comment by jettisonjoe** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[pylintrc, line 44 \[r4\]](https://reviewable.io:443/reviews/google/openhtf/402#-KPS_tmRUCljQtOzyMYI:-KPnTLQAZPkyjnxITUpz:blas5yh) ([raw file](https://github.com/google/openhtf/blob/3ce46080f17b22bf99da05a9e26695db980d0a5f/pylintrc#L44)):*
<details><summary><i>Previously, fahhem (Fahrzin Hemmati) wrote…</i></summary>
> protected-access is really beneficial, and if we're getting a bunch of them I'd be surprised. abstractmethod shouldn't show up much in this codebase either, and I think it's worth the pylint disable comments since it'll usually be followed up with which abstract methods weren't implemented
</details>
Agreed. Fixed.

---

*[openhtf/bin/units_from_xls.py, line 122 \[r4\]](https://reviewable.io:443/reviews/google/openhtf/402#-KPSdFWzCqY6ykNvIx9t:-KPnRoryXLbIuZBrteZM:b-omceqm) ([raw file](https://github.com/google/openhtf/blob/3ce46080f17b22bf99da05a9e26695db980d0a5f/openhtf/bin/units_from_xls.py#L122)):*
<details><summary><i>Previously, fahhem (Fahrzin Hemmati) wrote…</i></summary>
> You added this to pylintrc, but didn't remove it from here (is it anywhere else, too?)
</details>
Yeah, tons. Fixed now.

---

*[openhtf/io/http_api.py, line 110 \[r4\]](https://reviewable.io:443/reviews/google/openhtf/402#-KPSfZ__b6bLWhl0TJ8i:-KPnRsotlZOjC-5vtbNO:ba11hx3) ([raw file](https://github.com/google/openhtf/blob/3ce46080f17b22bf99da05a9e26695db980d0a5f/openhtf/io/http_api.py#L110)):*
<details><summary><i>Previously, fahhem (Fahrzin Hemmati) wrote…</i></summary>
> If station API is tested and used by someone sure. I haven't been able to import it yet due to the API changes and looming testing deadlines so I don't know if it works for us
</details>
Yeah, but the framework doesn't use the http_api any more. If you're using http_api in your own way aside from how the framework previously was set up to do so automatically, can you just pull the v0.9.0 tag?

---

*[pylint_plugins/conf_plugin.py, line 26 \[r5\]](https://reviewable.io:443/reviews/google/openhtf/402#-KP_CWWv3B3PmX9AKveJ:-KPnSzwzmYHKI2AgZ7DR:b-hyt2rr) ([raw file](https://github.com/google/openhtf/blob/27cebec4ead3df2737be3781984aaf0d2ded11ee/pylint_plugins/conf_plugin.py#L26)):*
<details><summary><i>Previously, fahhem (Fahrzin Hemmati) wrote…</i></summary>
> This is a namespace of variables? Why not just module-level variables?
</details>
Hmm, fair enough.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/openhtf/402)*

**Comment by jettisonjoe** [comment]
PTAL

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/openhtf/402#-:-KPnTgflfuCF1m6ZKcMH:bb71pro)*

**Comment by fahhem** [comment]
Reviewed 13 of 13 files at r7.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[openhtf/io/http_api.py, line 110 \[r4\]](https://reviewable.io:443/reviews/google/openhtf/402#-KPSfZ__b6bLWhl0TJ8i:-KPntugSu02TfokzZ6GN:b-84biz2) ([raw file](https://github.com/google/openhtf/blob/3ce46080f17b22bf99da05a9e26695db980d0a5f/openhtf/io/http_api.py#L110)):*
<details><summary><i>Previously, jettisonjoe (Joe Ethier) wrote…</i></summary>
> Yeah, but the framework doesn't use the http_api any more. If you're using http_api in your own way aside from how the framework previously was set up to do so automatically, can you just pull the v0.9.0 tag?
</details>
Oh I see. We're not using it directly at all, so we should just delete it (in another PR).

---

*[pylint_plugins/conf_plugin.py, line 42 \[r7\]](https://reviewable.io:443/reviews/google/openhtf/402#-KPntRQjnPTE9WjNktUl:-KPntRQjnPTE9WjNktUm:b-yafyl) ([raw file](https://github.com/google/openhtf/blob/b8e6337a50da490433603374fa2f5e19adce4077/pylint_plugins/conf_plugin.py#L42)):*
> ```Python
>     # Keep track of the current root, refreshing the locals if it changes.
>     if not CURRENT_ROOT or CURRENT_ROOT != node.root():
>       CURRENT_ROOT = node.root()
> ```

oh, you'll want to add `global CURRENT_ROOT` at the top for this to work

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/openhtf/402)*

**Comment by jettisonjoe** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[openhtf/io/http_api.py, line 110 \[r4\]](https://reviewable.io:443/reviews/google/openhtf/402#-KPSfZ__b6bLWhl0TJ8i:-KPo6j9QT8ktzZlOlooY:bbs8i7m) ([raw file](https://github.com/google/openhtf/blob/3ce46080f17b22bf99da05a9e26695db980d0a5f/openhtf/io/http_api.py#L110)):*
<details><summary><i>Previously, fahhem (Fahrzin Hemmati) wrote…</i></summary>
> Oh I see. We're not using it directly at all, so we should just delete it (in another PR).
</details>
Another PR for this SGTM.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/openhtf/402)*

**Comment by jettisonjoe** [comment]
I addressed all the feedback, but in the process I found #410. Since our pylint score is still at 9.73 even with the bug, I'm going to file it for later and not block this merge because of it. Thanks for the review!

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/openhtf/402#-:-KPooVaiAlUcCT0uCmGH:b-7ubqhl)*

**Pull request merged**
