### PR TITLE
python3 WIP

### PR DESCRIPTION
**Pull request by charlesnicholson**
All of the Python3 migration changes I've made so far. Tests pass but Brandon discovered lots of things that don't work. This PR is just to get my repo changes into the mainline so we can develop publicly there instead of in my github.

(might also need to roll back the pathing changes I made in setup.py around the protobufs)

### CODE REVIEW

**Comment by fahhem** [comment]
Update the travis yaml to use python 3 for the tests

**Comment by wallacbe** [comment]
Add python3-dev to packages in CONTRIBUTING.md

**Comment by wallacbe** [comment]
Is the a reason why Travis would show and error vs setting up a local virtualenv with Python3.6 and having it pass running:
python setup.py test --pytest-cov=term-missing

**Comment by charlesnicholson** [comment]
Yeah, I noticed that too, I'm having trouble recreating the failure. I'll take a closer look sometime soon.

In the meantime, I'm seeing what looks like some nondeterminism in the tests, Re-running "python3 setup.py test" a few times gave me this failure in test_cancel_start:

>     self.assertLessEqual(record.end_time_millis, record.start_time_millis)
E     AssertionError: 1511967289989 not less than or equal to 1511967289988

Those look like real values, not fake ones? Anyway, I'll look into that as well.

**Comment by jettisonjoe** [comment]
Most of the times I've seen that I've had uncommitted changes on my local repo. You can try clearing Travis's cache from the web GUI, though.

**Comment by charlesnicholson** [comment]
Thanks, seems worth a try. I don't see any obvious configuration that I have access too, am I just being dense or do you need to be a project maintainer to clear the cache?

**Comment by wallacbe** [comment]
I have access to Travis.  I deleted the cache for that PR and started a build (which failed).  What protoc version does Travis use?  I don't see that in the logs

**Comment by jettisonjoe** [comment]
That's a good question; I don't know. Our travis.yml file only specifies the package libprotobuf-dev not a specific version. Now that you mention it, I did have issues compiling the protos recently on a Debian-unstable machine and I think it was due to the new protoc breaking the way we use our protos.

**Comment by jettisonjoe** [comment]
Try changing this line in `setup.py` to require protobuf version `3.2.0` instead.
```
'protobuf>=2.6.1,<4.0'
```

**Comment by wallacbe** [comment]
I searched through Trusty raw logs, looks like protoc 2.5.0 ?
Get:27 http://archive.ubuntu.com/ubuntu trusty/main amd64 protobuf-compiler amd64 2.5.0-9ubuntu1 [19.8 kB]

Looks like Python3 is supported in protoc versions 3+

My local machine is:
protoc --version
libprotoc 3.5.0

Travis has a blurb in their documentation about creating a script and using wget to install protoc
https://docs.travis-ci.com/user/installing-dependencies/

**Comment by jettisonjoe** [comment]
We should consider adding a protoc version check and download to setup.py as an alternative to doing it in a travis script.

**Comment by charlesnicholson** [comment]
Cool, the travis fixes from @wallacbe worked, though they're not what @jettisonjoe recommended. I'm in favor of this PR going in to origin/python3 as-is so that Brandon (and maybe others?) can independently contribute to it rather than open fake PR's for me to copy-paste into this one :)

**Comment by wallacbe** [comment]
LGTM

**Pull request merged**
