### PR TITLE
Allow protobuf 3.x

### PR DESCRIPTION
**Pull request by DanLipsitt**
Homebrew, Debian stable, and Ubuntu 16.10 and later all ship version 3.x of the protobuf compiler (`protoc`). 

When the python protobuf library doesn't  match the version of `protoc`, it can result in errors like this:
```shellsession
$ python setup.py test
______________________________ ERROR collecting test/output/callbacks/callbacks_test.py ______________________________

test/output/callbacks/callbacks_test.py:27: in <module>
    from openhtf.output.callbacks import mfg_inspector
openhtf/output/callbacks/mfg_inspector.py:44: in <module>
    from openhtf.output.proto import guzzle_pb2
openhtf/output/proto/guzzle_pb2.py:23: in <module>
    serialized_pb=_b('\n\x0cguzzle.proto\x12\x07openhtf\"N\n\x0fTestRunEnvelope\x12*\n\x0cpayload_type\x18\x02 \x01(\x0e\x32\x14.openhtf.PayloadType\x12\x0f\n\x07payload\x18\x03 \x01(\x0c*S\n\x0bPayloadType\x12\x17\n\x13\x43OMPRESSED_TEST_RUN\x10\x01\x12\x13\n\x0f\x43OMPRESSED_VARZ\x10\x02\x12\x16\n\x12\x43OMPRESSED_LOGFILE\x10\x03')
E   TypeError: __init__() got an unexpected keyword argument 'syntax'
```

Tests pass when the python protobuf library is allowed to be version 3.x.

### CODE REVIEW

**Comment by fahhem** [comment]
Can you check that this works when protoc is 3 and protobuf is 2? I'm pretty sure it doesn't work, but if it does then LGTM

**Comment by fahhem** [comment]
Oh wait, that's the problem you're fixing. I meant when protoc is 2 and protobuf is 3

**Comment by DanLipsitt** [comment]
The Travis run for this PR used `protobuf-compiler_2.4.1-1ubuntu2_amd64.deb` and protobuf 3.3.0.

**Comment by DanLipsitt** [comment]
PTAL.

**Pull request merged**
