### PR TITLE
add indent=2 to json in mfg_inspector

### PR DESCRIPTION
**Pull request by wallacbe**

### CODE REVIEW

**Comment by wallacbe** [comment]
PTAL

**Comment by jettisonjoe** [comment]
LGTM, but I want to get a quick LGTM from @grybmadsci or @fahhem before we merge, since I haven't been super involved in the mfg_inspector stuff.

**Comment by wallacbe** [comment]
purpose is to homogenize with the examples and make it more human readable

**Comment by fahhem** [comment]
You're probably going to need to update the tests, but lgtm from me

**Comment by jettisonjoe** [comment]
Oddly enough, the tests are passing right now, and the modded lines are covered according to the log. I could dig into the stringification of protobufs, or I could just not question it...

**Comment by grybmadsci** [comment]
LGTM, i think the tests are passing because i updated the test to exclude certain redundant stuff, like this JSON text.

**Pull request merged**
