### PR TITLE
Removed issue stats images from readme

### PR DESCRIPTION
**Pull request by CameronSamuels**
These are broken images every now and then.

Originated from pr #605 but I deleted the fork.

### CODE REVIEW

**Comment by jettisonjoe** [comment]
It might be cool to leave maybe a single link to the issuestats page even though the badges are being removed.

**Comment by jettisonjoe** [comment]
That CI check failing has to do with the PyOpenSSL version I think. We need to update our setup.py to require a newer version.

**Comment by CameronSamuels** [comment]
I just noticed that too.

**Comment by fahhem** [comment]
I don't think this sort of change should require multiple maintainers to approve. Sorry that this one took so long and so many changes to get in

**Pull request merged**
