### PR TITLE
Include unbuilt protos in the package not just the source repo.

### PR DESCRIPTION
**Pull request by jettisonjoe**
This change is [Reviewable](https://reviewable.io/reviews/google/openhtf/705)

### CODE REVIEW

**Comment by fahhem** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/openhtf/705)*

**Comment by jettisonjoe** [comment]
Removed version bump so we can do that in a separate PR. I have a theory as to when this broke. Looking into it now.

**Comment by jettisonjoe** [comment]
My theory was that we were doing wheel-based distribution before and switched to source-based distribution at some point (multi-platform support?), but I can't find where we would have had to change that.

**Comment by jettisonjoe** [comment]
Fixes #693

**Pull request merged**
