### PR TITLE
Show failed measurement-less phases as failed

### PR DESCRIPTION
**Pull request by lalten**
Show failed measurement-less phases as failed in web ui.

By adding `skip`, `error` states and using PhaseRecord.outcome instead of checking measurement.status.

You will need to rebuild the web app after these changes. That's not included in this PR.

image
image

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/openhtf/1020)

### CODE REVIEW

**Comment by lalten** [comment]
@cricdecyan should I add a commit that includes a rebuilt webfront based on latest master? Or how would you like to proceed here?

**Comment by cricdecyan** [comment]
@lalten I have to upstream some of our internal changes to OpenHTF, after that it will be time to look at this PR.

**Comment by cricdecyan** [comment]
@lalten Please update this PR so I can review it. Thanks.

**Comment by lalten** [comment]
I rebased to latest master, there were no conflicts

**Review by cricdecyan — APPROVED** [review]

**Pull request merged**
