### PR TITLE
Web GUI plugin support and example plugin

### PR DESCRIPTION
**Pull request by maddychan**
Change frontend and backend structure to accommodate adding plugins, and add example plugin in examples folder

### CODE REVIEW

**Comment by maddychan** [comment]
@jettisonjoe @grybmadsci

**Comment by fahhem** [comment]
What confuses me is that there's a ton of history-related code for the frontend mixed in here. Any chance that could be put in its own PR or mentioned in the title of this one?

**Comment by fahhem** [comment]
Oh, and it's in the old frontend directory :)

**Comment by fahhem** [comment]
Reviewed 17 of 29 files at r1, 9 of 13 files at r2, 5 of 5 files at r3.
Review status: 27 of 30 files reviewed at latest revision, 14 unresolved discussions, some commit checks failed.

---

*[examples/example_plugin/setup.py, line 3 \[r3\]](https://reviewable.io:443/reviews/google/openhtf/432#-KQhSEW5VSxrjnYsPXnA:-KQhSEW5VSxrjnYsPXnB:b-dcndo0) ([raw file](https://github.com/google/openhtf/blob/b280319bd6d4ed170597f3e707d669fcf7ab7e6e/examples/example_plugin/setup.py#L3)):*
> ```Python
> from setuptools import setup
> 
> setup(name='example_plugin',
> ```

Is this a separate python package?

---

*[examples/example_plugin/example_plugin/__init__.py, line 8 \[r3\]](https://reviewable.io:443/reviews/google/openhtf/432#-KQhSep3ASrcuEmHNNmD:-KQhSep3ASrcuEmHNNmE:bbhefgp) ([raw file](https://github.com/google/openhtf/blob/b280319bd6d4ed170597f3e707d669fcf7ab7e6e/examples/example_plugin/example_plugin/__init__.py#L8)):*
> ```Python
> class ExampleHandler(tornado.web.RequestHandler):
> 
> 	def initialize(self, station_store, host, port, path):
> ```

you used tabs here, please use 2 spaces instead. The configs dict below looks incorrect in GitHub but correct here because tabs are rendered according to the editor rather than universally

---

*[examples/example_plugin/example_plugin/plugin/main.ts, line 37 \[r3\]](https://reviewable.io:443/reviews/google/openhtf/432#-KQhUJ3nwiQHh9levRKF:-KQhUJ3nwiQHh9levRKG:bkh3nks) ([raw file](https://github.com/google/openhtf/blob/b280319bd6d4ed170597f3e707d669fcf7ab7e6e/examples/example_plugin/example_plugin/plugin/main.ts#L37)):*
> ```XML
>    */
>   ngOnInit() {
>     this.exampleService.requestData();
> ```

A couple things:

* Why split this into a service and a component?
* You call `requestData()` then `getData()`, but `requestData()` is actually asynchronous, so `getData()` will return the old data (that will magically get patched later by jsonpatch). This should either pass a callback to `requestData()` or `requestData()` should return the data that will be magically patched later to make that magic a little more explicit

---

*[openhtf/io/frontend/src/app/history.service.ts, line 51 \[r3\]](https://reviewable.io:443/reviews/google/openhtf/432#-KQhUsZ2a1MqDpOV0glS:-KQhUsZ2a1MqDpOV0glT:b-f42ksz) ([raw file](https://github.com/google/openhtf/blob/b280319bd6d4ed170597f3e707d669fcf7ab7e6e/openhtf/io/frontend/src/app/history.service.ts#L51)):*
> ```XML
> 
>   setStationId(id: string){
>     this.station_id = id;
> ```

What does this look like? I can imagine it being a hostname, hostname:port, uuid, etc

---

*[openhtf/io/frontend/src/app/history.ts, line 32 \[r3\]](https://reviewable.io:443/reviews/google/openhtf/432#-KQhV-0gKN-G4OvTVDJO:-KQhV-0hp01pXUJjlOO8:b-91j66d) ([raw file](https://github.com/google/openhtf/blob/b280319bd6d4ed170597f3e707d669fcf7ab7e6e/openhtf/io/frontend/src/app/history.ts#L32)):*
> ```XML
>   selector: 'history',
>   template: `
>     <div id="history">
> ```

This template is much more deserving of being split out than the example plugin's :) I sort of prefer the inline version anyway, since the tools check the html, so I'd just convert the example plugin to be inline, too

---

*[openhtf/io/frontend/src/app/history.ts, line 78 \[r3\]](https://reviewable.io:443/reviews/google/openhtf/432#-KQhVMUGhVSnhTu1a2Ai:-KQhVMUGhVSnhTu1a2Aj:b-youlh8) ([raw file](https://github.com/google/openhtf/blob/b280319bd6d4ed170597f3e707d669fcf7ab7e6e/openhtf/io/frontend/src/app/history.ts#L78)):*
> ```XML
> 
>   public ngOnInit(): any{
>     this.tests = this.historyService.getTests();
> ```

When is `requestTests()` called?

---

*[openhtf/io/frontend/src/app/station.prompt.html, line 25 \[r3\]](https://reviewable.io:443/reviews/google/openhtf/432#-KQhVQrAYPr_X3Dl4mkv:-KQhVQrAYPr_X3Dl4mkw:b-f5r4t2) ([raw file](https://github.com/google/openhtf/blob/b280319bd6d4ed170597f3e707d669fcf7ab7e6e/openhtf/io/frontend/src/app/station.prompt.html#L25)):*
> ```HTML
>        (click)="sendResponse(null, framework.prompt.id)">OK</a>
>   </div>
> </div>
> ```

I think this file was moved incorrect?

---

*[openhtf/output/web_gui/__init__.py, line 350 \[r3\]](https://reviewable.io:443/reviews/google/openhtf/432#-KQhVy_XjWhTs7dqba8w:-KQhVy_XjWhTs7dqba8x:b-ozl0m) ([raw file](https://github.com/google/openhtf/blob/b280319bd6d4ed170597f3e707d669fcf7ab7e6e/openhtf/output/web_gui/__init__.py#L350)):*
> ```Python
>     ] + dash_router.urls + station_router.urls
> 
>     #Add plugins into handler_routes
> ```

nit: comments should have a space after the #

---

*[openhtf/output/web_gui/src/README.md, line 26 \[r3\]](https://reviewable.io:443/reviews/google/openhtf/432#-KQhWBcIxWzndOjZy4-e:-KQhWBcIxWzndOjZy4-f:b-ovo5r0) ([raw file](https://github.com/google/openhtf/blob/b280319bd6d4ed170597f3e707d669fcf7ab7e6e/openhtf/output/web_gui/src/README.md#L26)):*
> ```Markdown
> ```
> /example_plugin
> 	|
> ```

don't use tabs here (and below), prefer 4 spaces instead.

---

*[openhtf/output/web_gui/src/update_plugins.py, line 219 \[r3\]](https://reviewable.io:443/reviews/google/openhtf/432#-KQhX0sRMacItHIil6-8:-KQhX0sRMacItHIil6-9:b-tm3nuq) ([raw file](https://github.com/google/openhtf/blob/b280319bd6d4ed170597f3e707d669fcf7ab7e6e/openhtf/output/web_gui/src/update_plugins.py#L219)):*
> ```Python
>     new_file.flush()
> 
>   if os.path.exists("./app/station.html"):
> ```

why not write into that file directly? Also, what if I run this from the wrong folder? Either change your working directory or error out early if this is running from another directory

---

*[openhtf/output/web_gui/src/app/station.header.html, line 40 \[r3\]](https://reviewable.io:443/reviews/google/openhtf/432#-KQhXPgk9RrOef4gI_rX:-KQhXPgl-5Y9tC41nQlm:b-fjrwl4) ([raw file](https://github.com/google/openhtf/blob/b280319bd6d4ed170597f3e707d669fcf7ab7e6e/openhtf/output/web_gui/src/app/station.header.html#L40)):*
> ```HTML
>     </div>
>   </div>
>   
> ```

Scout? ;)

---

*[openhtf/output/web_gui/src/app/station.testheader.html, line 53 \[r3\]](https://reviewable.io:443/reviews/google/openhtf/432#-KQhXef5U_s9bY2y1i9b:-KQhXef5U_s9bY2y1i9c:btjpc09) ([raw file](https://github.com/google/openhtf/blob/b280319bd6d4ed170597f3e707d669fcf7ab7e6e/openhtf/output/web_gui/src/app/station.testheader.html#L53)):*
> ```HTML
>     <div class="test-status-tag">
>       {{status | simplifyStatus}}
>       <div *ngIf="canStar">
> ```

star? The time is removed?

---

*[openhtf/output/web_gui/src/package.json~, line 0 \[r2\]](https://reviewable.io:443/reviews/google/openhtf/432#-KQhXzm2c3J-WkWVKzLi:-KQhXzm2c3J-WkWVKzLj:b4nwfze) ([raw file](https://github.com/google/openhtf/blob/978de910ecda0839ba0c66b5c951524c16aed02d/openhtf/output/web_gui/src/package.json~#L0)):*
backup file?

---

*[openhtf/output/web_gui/src/README.md~, line 0 \[r3\]](https://reviewable.io:443/reviews/google/openhtf/432#-KQhXwZ6YTwMUca3_QOB:-KQhXwZ6YTwMUca3_QOC:b4nwfze) ([raw file](https://github.com/google/openhtf/blob/b280319bd6d4ed170597f3e707d669fcf7ab7e6e/openhtf/output/web_gui/src/README.md~#L0)):*
backup file?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/openhtf/432)*

**Comment by maddychan** [comment]
- For the history files: they were actually supposed to go into the history plugin and not here; I deleted the files here and made the changes on my local machine - thanks for catching that/code reviewing the files! 
-Yes, the example plugin is a separate package
-For the canStar variable in the station header, it was so that we could have a more minimal list of headers in the history view. Maybe it should be renamed to isHistoryList or isTestList?

**Comment by jettisonjoe** [comment]
Rather than go through the merge conflict resolution, I'm going to close this for now. I believe the consensus is now to move in a different direction (replace the station API and upstream one of the other internal frontend implementations).

**Pull request closed without merging**
