### PR TITLE
Fixed bug with 'show image with user.prompt'

### PR DESCRIPTION
**Pull request by Spudmn**
One line was over written with a previous merge
that stopped user.prompt with images from working.

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/openhtf/1071)

### CODE REVIEW

**Comment by Spudmn** [comment]
I have just noticed that this is a duplicate of this PR https://github.com/google/openhtf/pull/962

**Comment by dbhatman** [comment]
Thanks for this change, I am going to close and reopen this to try to get our import automation to trigger. Otherwise I will do a manual import.

**Comment by Spudmn** [comment]
@dbhatman you can probably close PR https://github.com/google/openhtf/pull/962 as it is the same as this fix

**Comment by dbhatman** [comment]
Done thanks! I was waiting for this to get merged before closing the other one out

**Pull request merged**
