### PR TITLE
Allow overriding the argument parser

### PR DESCRIPTION
**Pull request by fahhem**
Added some docs for overriding and added a keyword arg to `Test.Configure()`

Also put arg parsing before logging setup to allow args to modify logging.

### CODE REVIEW

**Comment by fahhem** [comment]
Added `parse_all_args` because there is a `Configure()` call in `__init__()` that can cause problems.

If the library user wants to allow new arguments, they need to provide their own `ArgumentParser()` instance to `Configure()`. If they want to disallow unknown args, they pass `parse_all_args=True` in as well. By default, openhtf won't disallow unknown args because the current API doesn't allow that to happen without punishing users with external arguments.

**Comment by grybmadsci** [comment]
This seems like a bit much complexity, what are the reasons for not simply changing `parse_args` to `parse_known_args`?

**Comment by fahhem** [comment]
An attempt to see if you cared for the strictness of it. Since you don't, I'll drop any of that related code in a sec

**Comment by fahhem** [comment]
Alright, done now

**Comment by grybmadsci** [comment]
Ah, I mostly just don't know the specifics of any side effects of calling `parse_args()` multiple times.  This is a little easier to follow I think, though, so until there's a need to make it more complicated, might as well keep it simple.  Thanks for the fix!

**Pull request merged**
