### PR TITLE
Edit pylintrc file

### PR DESCRIPTION
**Pull request by maddychan**
Update the regex in some of the fields, make sure the pylint adheres to google style standards as much as possible

### CODE REVIEW

**Comment by maddychan** [comment]
Hey Googlebot, I turned off the email privacy on my github account - I think that was the problem.

**Comment by fahhem** [comment]
Can we separate updating pylintrc from making the codebase name-style compliant? This changes the APIs in OpenHTF rather significantly and can cause downstream pain if we don't meter this out.

**Comment by jettisonjoe** [comment]
@fahhem, yeah, we can separate it out. It's likely we're gonna let our PyPI launch slip by a few days, but I'd still like to make a solid attempt at complying with our updated pylint rules in prep for PyPI launch.

**Comment by grybmadsci** [comment]
Agreed, in particular we have a side-development branch in progress right now (station_api) with fairly extensive changes, and doing this right now would cause a ball of merge conflicts, let's wait until `station_api` is merged in to actually update the codebase to by new-pylintrc-compliant.

**Comment by jettisonjoe** [comment]
We'll split it so this PR is just the pylintrc changes. But @maddychan is making great progress on updating the codebase to comply and we should keep momentum going on that. I'll help with the rebase for that separate set of changes when the time comes. I don't think it will be that bad. Plus, git merge conflict resolution practice!

**Comment by maddychan** [comment]
Took out the commits regarding compliance to put in another commit; this now only contains the pylintrc changes

**Comment by grybmadsci** [comment]
LGTM for now, may need to update this as special cases come up, but for now let's get it merged :)

**Pull request merged**
