### PR TITLE
Expose public API with __all__ and minor formatting tweaks

### PR DESCRIPTION
**Pull request by dbhatman**
This replaces the need for https://github.com/google/openhtf/pull/1016

PiperOrigin-RevId: 478889967

- - -
This change is [Reviewable](https://reviewable.io/reviews/google/openhtf/1046)

### CODE REVIEW

**Comment by lalten** [comment]
Thanks for taking a stab at this @dbhatman. This does indeed fix the issue with Pylance described in #1016, but it adds another problem: Go-to-definition (in VS Code) will now always jump to `__init__.py` instead of the actual definition. The solution in #1016 does not show this behavior, it jumps right into the actual source file.

**Comment by dbhatman** [comment]
> Thanks for taking a stab at this @dbhatman. This does indeed fix the issue with Pylance described in #1016, but it adds another problem: Go-to-definition (in VS Code) will now always jump to `__init__.py` instead of the actual definition. The solution in #1016 does not show this behavior, it jumps right into the actual source file.

Thanks for following up @lalten 

The behavior (ie requires the second click of go-to) you are seeing is pretty typical in projects following google style guides because of this style rule: https://google.github.io/styleguide/pyguide.html#22-imports. As part of cleaning up some things on our side so we can more closely align with the style guide, I am going to suggest we go forward with this but I'll keep this issue in mind and see if I can come up with an alternate solution that still complies.

**Comment by lalten** [comment]
Lgtm then. If you're in the process of cleaning up it would be great to give the pylintrc a refresh as that's currently broken (references deleted plugins and such).

**Comment by dbhatman** [comment]
Ah was just looking at the pylintrc and scratching my head at the plugins! 

(and cleaning that up broke this PR 😆)

**Review by glados-verma — APPROVED** [review]

**Pull request merged**
