### PR TITLE
Revise package structure as discussed in issue #314.

### LINKED ISSUE #314: Review and revise package structure.
Over time it has become clear that out package structure could use a little more work. Here's a proposal for a reorg. Let's discuss. I'm hoping to get the reorg done before PyPI launch, as it will affect test scripts' imports.

```
.-----------------.
|     openhtf     |
|-----------------|
| Python package. |
'-----------------'
        |
        |    .--------------------------------------------------------------.
        |    |                             core                             |
        |--->|--------------------------------------------------------------|
        |    | Framework internals that manage test state and execution.    |
        |    | The contents of this submodule shouldn't normally need to be |
        |    | accessed from outside the library.                           |
        |    '--------------------------------------------------------------'
        |
        |    .------------------------------------------------------------.
        |    |                           output                           |
        |--->|------------------------------------------------------------|
        |    | Manages the framework's output, including UI, logging, and |
        |    | test records.                                              |
        |    '------------------------------------------------------------'
        |
        |    .-----------------------------------------------------------.
        |    |                           plugs                           |
        |--->|-----------------------------------------------------------|
        |    | Extensions for interfacing with various hardware, such as |
        |    | test equipment and DUT's.                                 |
        |    '-----------------------------------------------------------'
        |
        |    .--------------------------------------------------------------.
        |    |                             util                             |
        |    |--------------------------------------------------------------|
        '--->| Generic utility functions and miscellaneous tools. The       |
             | contents of this submodule should be general enough to be    |
             | useable outside of OpenHTF, meaning it should not be         |
             | dependent on other code in the OpenHTF package itself.       |
             '--------------------------------------------------------------'
```

### PR DESCRIPTION
**Pull request by jettisonjoe**
Fixes #314

See the [original staged PR](https://github.com/jettisonjoe/openhtf/pull/2) for previous review history.

---
This change is [Reviewable](https://reviewable.io/reviews/google/openhtf/411)

### CODE REVIEW

**Comment by fahhem** [comment]
:lgtm:

---

Reviewed 233 of 233 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[CONTRIBUTING.md, line 169 \[r1\]](https://reviewable.io:443/reviews/google/openhtf/411#-KPoy1Ty8O4a9yZBR5_F:-KPoy1Ty8O4a9yZBR5_G:b-14zv80) ([raw file](https://github.com/google/openhtf/blob/7889cc997fdbc0dd03852a6ca0d4fb54e7f61f08/CONTRIBUTING.md#L169)):*
> ```Markdown
>     |     |
>     |     |
>     |     |-> plugs
> ```

Where do we want folks to add their plugs to? Should they go in here (openhtf/plugs) or contrib/plugs? It seems contrib/ is a good place for that boundary of "openhtf cannot depend on this, but openhtf users can"

---

*[examples/all_the_things.py, line 32 \[r1\]](https://reviewable.io:443/reviews/google/openhtf/411#-KPoyZiVVvaOTJMEJX-e:-KPoyZiWLjJkLg0_9sCj:b-hdyhn4) ([raw file](https://github.com/google/openhtf/blob/7889cc997fdbc0dd03852a6ca0d4fb54e7f61f08/examples/all_the_things.py#L32)):*
> ```Python
> 
> 
> PROMPT_MGR = user_input.get_prompt_manager()
> ```

not used?

---

*[openhtf/__init__.py, line 52 \[r1\]](https://reviewable.io:443/reviews/google/openhtf/411#-KPozhZptX2v0A4hauFp:-KPozhZq5C7ekhalmGyF:buivmte) ([raw file](https://github.com/google/openhtf/blob/7889cc997fdbc0dd03852a6ca0d4fb54e7f61f08/openhtf/__init__.py#L52)):*
> ```Python
> 
> 
> __all__ = sys.modules['openhtf'].__dict__.setdefault('__all__', []).extend([
> ```

This is an odd construct that, while it technically works, goes about it a weird way. Why not just do this:

```py
__all__ = [
    'openhtf.util.utils',
    ...
]
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/openhtf/411#-:-KPp06inoiI_vVurvY-E:bnfp4nl)*

**Comment by jettisonjoe** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[CONTRIBUTING.md, line 169 \[r1\]](https://reviewable.io:443/reviews/google/openhtf/411#-KPoy1Ty8O4a9yZBR5_F:-KPsKLemPouhsWnsGNh1:b-k94hv3) ([raw file](https://github.com/google/openhtf/blob/7889cc997fdbc0dd03852a6ca0d4fb54e7f61f08/CONTRIBUTING.md#L169)):*
<details><summary><i>Previously, fahhem (Fahrzin Hemmati) wrote…</i></summary>
> Where do we want folks to add their plugs to? Should they go in here (openhtf/plugs) or contrib/plugs? It seems contrib/ is a good place for that boundary of "openhtf cannot depend on this, but openhtf users can"
</details>
Hmm, sgtm! I'll create a plugs dir in contrib to house those. We probably want to move even our included plugs there and just have the plug _system_ in `openhtf.plugs`.

---

*[examples/all_the_things.py, line 32 \[r1\]](https://reviewable.io:443/reviews/google/openhtf/411#-KPoyZiVVvaOTJMEJX-e:-KPsKmfoNWWe0Dy4NiWT:bt2vr1b) ([raw file](https://github.com/google/openhtf/blob/7889cc997fdbc0dd03852a6ca0d4fb54e7f61f08/examples/all_the_things.py#L32)):*
<details><summary><i>Previously, fahhem (Fahrzin Hemmati) wrote…</i></summary>
> not used?
</details>
Fixed.

---

*[openhtf/__init__.py, line 52 \[r1\]](https://reviewable.io:443/reviews/google/openhtf/411#-KPozhZptX2v0A4hauFp:-KPsKq4QSIoEfUAwRiF3:b-mm96cd) ([raw file](https://github.com/google/openhtf/blob/7889cc997fdbc0dd03852a6ca0d4fb54e7f61f08/openhtf/__init__.py#L52)):*
<details><summary><i>Previously, fahhem (Fahrzin Hemmati) wrote…</i></summary>
> This is an odd construct that, while it technically works, goes about it a weird way. Why not just do this:
> 
> ```py
> __all__ = [
>     'openhtf.util.utils',
>     ...
> ]
> ```
</details>
I think I did this because hard-setting `__all__` was losing some stuff. I'll take another look.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/openhtf/411)*

**Comment by jettisonjoe** [comment]
Review status: 118 of 135 files reviewed at latest revision, 3 unresolved discussions.

---

*[openhtf/__init__.py, line 52 \[r1\]](https://reviewable.io:443/reviews/google/openhtf/411#-KPozhZptX2v0A4hauFp:-KPtIrq2QxqBx0EuMQXP:b-t76fac) ([raw file](https://github.com/google/openhtf/blob/7889cc997fdbc0dd03852a6ca0d4fb54e7f61f08/openhtf/__init__.py#L52)):*
<details><summary><i>Previously, jettisonjoe (Joe Ethier) wrote…</i></summary>
> I think I did this because hard-setting `__all__` was losing some stuff. I'll take another look.
</details>
Actually, since we're no longer recommending importing *, maybe it doesn't make sense to even use `__all__` after all.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/openhtf/411)*

**Comment by grybmadsci** [comment]
LGTM

**Pull request merged**
