### PR TITLE
use format in output callbacks

### PR DESCRIPTION
**Pull request by wallacbe**
https://github.com/google/openhtf/issues/311

### CODE REVIEW

**Comment by wallacbe** [comment]
PTAL

**Comment by fahhem** [comment]
I'd like to keep backwards compatibility if possible, so I think we should use the mechanism from measurements' WithArgs that checks for { in the string and chooses the appropriate interpolation based on that.

**Comment by wallacbe** [comment]
Made change, PTAL

**Comment by grybmadsci** [comment]
LGTM, will merge once there's a second LGTM in case I missed something.

**Comment by fahhem** [comment]
LGTM, thanks Brandon!

**Pull request merged**
