### PR TITLE
Rename to test_exectuor.py

### PR DESCRIPTION
**Pull request by kdsudac**
Renaming core/__init__.py to core/test_executor.py.  Will make logging statements more meaningful and eaiser to distinguish between phase_executor and test_executor.

### CODE REVIEW

**Comment by jettisonjoe** [comment]
Seems a bit arbitrary, but sure.

**Comment by kdsudac** [comment]
Fixed merge conflict.

**Comment by fahhem** [comment]
The module name shows up in tracebacks often, and looking at `__init__` everywhere, especially in the complicated executor logic, isn't debug friendly

**Comment by fahhem** [comment]
Hmm, does github not handle renames well?

**Comment by kdsudac** [comment]
Just tripped over my other small PR that was merge in so I needed to fix minor conflict.

I'm trying to keep my PR's small so they are easier to review, but kinda backfired in this case.

**Comment by fahhem** [comment]
Hmm, still not showing it as a move, but a whole new file. Did you make any significant changes?

**Comment by kdsudac** [comment]
Didn't make any changes in this PR, just moved.  

I think the problem might be I didn't just move, I did a move and replace:
1.   __init__.py --> test_executor.py
2.  new __init__.py (with only the imports)

**Comment by kdsudac** [comment]
Can someone please merge?

**Comment by Kenadia** [comment]
lgtm

**Comment by Kenadia** [comment]
Looking at other files in the repo, it seems like GitHub doesn't know how to track history across file renames, regardless of whether you move, move+replace, etc.

**Pull request merged**
