### PR TITLE
add sys.exit to Stop method in Test class

### PR DESCRIPTION
**Pull request by wallacbe**
https://github.com/google/openhtf/issues/291

### CODE REVIEW

**Comment by wallacbe** [comment]
PTAL

**Comment by fahhem** [comment]
`sys.exit()` will close the entire program, and should be avoided by libraries that aren't trying to wrap `sys`. This will make using `openhtf` as part of another program harder since `Stop` can kill the whole program rather than just `openhtf`.

The problem you're having is that the http api thread doesn't always die when it's supposed to, so you're stuck waiting for it to die (which it won't) when you hit Ctrl-C. @jettisonjoe said he has changes in the pipeline to fix this, so for now just add `test.Configure(http_api=None)`.

In the meantime, I might make the http api a daemon thread so if it's the last thread running, it won't hold the interpreter up.

**Comment by fahhem** [comment]
I mean `http_port=None`

**Comment by wallacbe** [comment]
II had that set already and have the issue:

```
  test.Configure(http_port=None, teardown_function=teardown)
  while True:
    test.Execute(test_start=triggers.PromptForTestStart())
```

**Comment by fahhem** [comment]
I replied in #291 and sent a new PR (#295) that should address this.

**Pull request closed without merging**
